-- Update CDFI program link
UPDATE programs 
SET url = 'https://www.cdfifund.gov/programs-training/programs/cdfi-program'
WHERE LOWER(name) LIKE '%cdfi%' OR LOWER(sponsor) LIKE '%cdfi%';

-- Insert new national grants
INSERT INTO programs (name, sponsor, description, url, type, level, state, rolling, status) VALUES
('DoorDash Local Business Disaster Relief Fund', 'DoorDash', '$5k–$15k to local businesses (restaurants, florists, grocers, etc.) impacted by natural disasters; administered with Hello Alice/GEN.', 'https://merchants.doordash.com/en-us/about/disaster-relief-fund', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Backing Historic Small Restaurants', 'National Trust + AmEx', '$50k grants to historic, locally significant restaurants to fund improvements and resilience.', 'https://savingplaces.org/historicrestaurants', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('eBay Up & Running Grants', 'eBay', '$10k cash + $500 tech stipend and seller resources for U.S. eBay sellers (annual program).', 'https://www.ebay.com/sellercenter/ebay-for-business/up-and-running-grants', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Verizon Small Business Digital Ready Grants', 'Verizon + LISC', '$10k grants for participants who complete platform learning/activities; multiple cycles per year via LISC.', 'https://www.lisc.org/our-initiatives/small-business/our-work/verizon-small-business-digital-ready/grant-program/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Amazon Business Small Business Grants', 'Amazon', 'Over $250k in grants/prizes to 15 U.S. small businesses (grand prize $25k) plus Business Prime and devices.', 'https://business.amazon.com/en/small-business/small-business-grants', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Arch Grants Startup Competition', 'Arch Grants', '$75k non-dilutive grants (plus relocation bonus) to innovative startups willing to HQ in St. Louis for a year.', 'https://archgrants.org/programs/startup-competition/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Main Street America - Backing Small Businesses', 'AmEx', '$10k grants for locally significant small businesses to support growth/resilience (nationwide).', 'https://mainstreet.org/about/partner-collaborations/backing-small-businesses', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Hello Alice Small Business Funding Center', 'Hello Alice', 'Curated, recurring grant programs across partners (typically $5k–$25k) with simple eligibility filters.', 'https://helloalice.com/funding/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('AAPI Strong Current Grants', 'National ACE', 'Rotating national grant programs (e.g., "Fast Break for Small Business") for AAPI-owned businesses.', 'https://www.aapistrong.com/current-grants', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Google for Startups Black Founders Fund', 'Google', 'Non-dilutive cash awards + Google support for U.S. Black-led startups.', 'https://startup.google.com/programs/black-founders-fund/united-states/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Cartier Women''s Initiative', 'Cartier', 'Equity-free awards plus coaching for women-owned impact businesses (global program, U.S. eligible).', 'https://www.cartierwomensinitiative.com/regional-awards', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Halstead Jewelry Grant', 'Halstead', 'Annual grant for emerging jewelry businesses (cash award + merchandise credit + publicity).', 'https://grant.halsteadbead.com/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Nav Small Business Grant Hub', 'Nav', 'Recurring national small-business grants and guidance (central info/app hub).', 'https://www.nav.com/resource/small-business-grants/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('USDA Value-Added Producer Grants', 'USDA', 'Grants for ag producers to create/market value-added products; planning and working-capital tracks.', 'https://www.rd.usda.gov/programs-services/business-programs/value-added-producer-grants', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('USDA Rural Business Development Grants', 'USDA', 'Grants supporting small rural business development through eligible entities.', 'https://www.rd.usda.gov/programs-services/business-programs/rural-business-development-grants', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('USDA Rural Development Business Programs', 'USDA', 'Portal to multiple federal small-business grant/loan programs for rural areas.', 'https://www.rd.usda.gov/programs-services/business-programs', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('SBIR/STTR Official Program Portal', 'Federal Government', 'Non-dilutive R&D grants across 11 federal agencies for innovative small businesses.', 'https://www.sbir.gov/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('NSF SBIR/STTR Phase I', 'NSF', 'Seed funding for deep-tech startups to develop high-impact innovations (non-dilutive).', 'https://www.nsf.gov/funding/opportunities/sbirsttr-phase-i-nsf-small-business-innovation-research-small-business', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('NSF SBIR/STTR Phase II', 'NSF', 'Follow-on non-dilutive awards to scale Phase I prototypes toward commercialization.', 'https://www.nsf.gov/funding/opportunities/sbirsttr-phase-ii-nsf-small-business-innovation-research-small-business', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('EPA SBIR', 'EPA', 'Grants for small businesses developing environmental/clean-tech solutions.', 'https://www.epa.gov/sbir', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('NIH SBIR/STTR', 'NIH', 'Biomedical and health innovation grants for small businesses.', 'https://seed.nih.gov/small-business-funding/sbir-sttr', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('DoD SBIR/STTR', 'DoD', 'Defense innovation topics with non-dilutive funding for small businesses.', 'https://www.dodsbirsttr.mil/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('DOE SBIR/STTR', 'DOE', 'Energy-tech R&D grants for startups/SMBs developing DOE-aligned innovations.', 'https://www.energy.gov/science/sbir/small-business-innovation-research-and-small-business-technology-transfer', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('NOAA SBIR', 'NOAA', 'Blue-tech, weather, climate and ocean innovations for small businesses.', 'https://oar.noaa.gov/sbir/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('NASA SBIR/STTR', 'NASA', 'Aerospace and dual-use tech grants for small businesses.', 'https://sbir.nasa.gov/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('U.S. Chamber of Commerce CO— Grants', 'U.S. Chamber of Commerce', 'Live list of national grants/programs with open applications and deadlines.', 'https://www.uschamber.com/co/run/business-financing/small-business-grants-and-programs', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Stacy''s Rise Project', 'PepsiCo', '$25k grants + mentorship/networking for women-founded food & beverage businesses.', 'https://www.stacyssnacks.com/riseproject', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Black Ambition Prize', 'Black Ambition', 'Prizes for ventures led by Black and Hispanic founders across sectors.', 'https://blackambitionprize.com/the-black-ambition-prize/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Comcast RISE', 'Comcast', 'Grant packages including tech makeovers, creative/advertising support and monetary grants in select U.S. markets.', 'https://www.comcastrise.com/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('IFundWomen Grants Hub', 'IFundWomen', 'Rotating corporate-sponsored grants for women-owned businesses (multiple industries).', 'https://www.ifundwomen.com/grants/apply-for-grants', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Hello Alice eBay Up & Running', 'Hello Alice + eBay', 'Program partner page with details, timelines, and recipient info.', 'https://helloalice.com/grants/ebay/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Hello Alice DoorDash Grant', 'Hello Alice + DoorDash', 'Program partner page with updates and recipient lists for the disaster relief grants.', 'https://helloalice.com/grants/doordash/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('Google for Startups Founders Funds', 'Google', 'Umbrella page for Black & Latino Founders Funds in the U.S.', 'https://startup.google.com/programs/black-founders-fund/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN'),
('OFN CDFI Locator', 'Opportunity Finance Network', 'Find mission-driven CDFIs; many run periodic small-business grant programs.', 'https://www.ofn.org/cdfi-locator/', 'GRANT', 'NATIONAL', NULL, true, 'OPEN');

-- Insert Arizona grants (using STATE level for all)
INSERT INTO programs (name, sponsor, description, url, type, level, state, county, city, rolling, status) VALUES
('Arizona State Trade Expansion Program', 'Arizona Commerce Authority + SBA', 'Export assistance grants for AZ small businesses entering or expanding in foreign markets (via ACA + SBA).', 'https://www.azcommerce.com/programs/arizona-state-trade-expansion-program/', 'GRANT', 'STATE', 'AZ', NULL, NULL, true, 'OPEN'),
('Arizona Community Foundation Grants Portal', 'Arizona Community Foundation', 'Year-round statewide grant opportunities for AZ nonprofits/enterprises aligned with community impact.', 'https://www.azfoundation.org/nonprofits/grant-opportunities/', 'GRANT', 'STATE', 'AZ', NULL, NULL, true, 'OPEN'),
('Maricopa SBDC Grants & Resources', 'Maricopa SBDC', 'Regularly updated list of AZ small-business grants and how to apply.', 'https://www.maricopa-sbdc.com/resources/small-business-grants-and-resources/', 'GRANT', 'STATE', 'AZ', NULL, NULL, true, 'OPEN'),
('Maricopa County Air Quality Incentive Programs', 'Maricopa County', 'Business grants/incentives for emission-reduction projects and clean equipment.', 'https://www.maricopa.gov/4783/Incentive-Programs-and-Grants', 'GRANT', 'STATE', 'AZ', 'Maricopa', NULL, true, 'OPEN'),
('City of Phoenix Business Assistance', 'City of Phoenix', 'Central page for Phoenix business funding opportunities (incl. tribal gaming & neighborhood grants).', 'https://www.phoenix.gov/business/business-assistance.html', 'GRANT', 'STATE', 'AZ', 'Maricopa', 'Phoenix', true, 'OPEN'),
('Arizona Commerce Authority SSBCI Programs', 'Arizona Commerce Authority', 'State portal for SSBCI-backed capital programs; includes pathways to partner CDFIs offering grants/credits.', 'https://www.azcommerce.com/ssbci/', 'GRANT', 'STATE', 'AZ', NULL, NULL, true, 'OPEN'),
('Prestamos CDFI Programs', 'Prestamos CDFI', 'AZ CDFI with grant/relief program portals posted when available; check for current AZ-specific rounds.', 'https://prestamoscdfi.org/phoenix/', 'GRANT', 'STATE', 'AZ', 'Maricopa', 'Phoenix', true, 'OPEN'),
('Arizona Commerce Authority International Trade', 'Arizona Commerce Authority', 'Export counseling + program links (incl. AZSTEP grant) for AZ firms expanding abroad.', 'https://www.azcommerce.com/small-business/checklist-items/exporting/i-would-like-information-on-expanding-to-international-markets/', 'GRANT', 'STATE', 'AZ', NULL, NULL, true, 'OPEN');